version: '3.3'
services:
    uaa-app:
        image: xmonline/xm-uaa:${IMAGE_TAG:-latest}
        networks:
            - xm2
        env_file:
            - ./env/uaa-app.env
        secrets:
            - source: UAA_SPRING_DATASOURCE_PASSWORD
              target: SPRING_DATASOURCE_PASSWORD
            - source: APPLICATION_RECAPTCHA_SECRETKEY
              target: APPLICATION_RECAPTCHA_SECRETKEY
            - source: APPLICATION_RECAPTCHA_PUBLICKEY
              target: APPLICATION_RECAPTCHA_PUBLICKEY
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
        logging:
            driver: syslog
            options:
                tag: uaa
                syslog-facility: local7

secrets:
    UAA_SPRING_DATASOURCE_PASSWORD:
        external: true
    APPLICATION_RECAPTCHA_PUBLICKEY:
        external: true
    APPLICATION_RECAPTCHA_SECRETKEY:
        external: true

networks:
    xm2:
        driver: overlay
