version: '3.3'
services:
    kafka:
        image: jbsukraine/apache-kafka:2.11-2.1.0
        networks:
            - xm2
        hostname: kafka
        environment:
            ZOO_HOST: zookeeper:2181
        volumes:
            - kafka:/tmp/kafka-logs
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
        logging:
            driver: syslog
            options:
                tag: kafka
                syslog-facility: local7

networks:
    xm2:
        driver: overlay
volumes:
    kafka:
